version: '3.9'
services:
  tester:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./target:/app/target
  web-app:
    build:
      context: web-app
    ports:
      - "3001:80"
  web-app-improved:
    build:
      context: web-app
    ports:
      - "3002:80"
